# Generated by Django 4.2 on 2025-04-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='calculation_errors',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='hos_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='route_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
